# テーマの設定
remote_theme: just-the-docs/just-the-docs

# サイトの基本情報
title: SF6 Stats Visualizer
url: "https://maruru2100.github.io"
baseurl: "/sf6-stats-visualizer"


# ダークモードの設定
color_scheme: dark

# ナビゲーションの設定（任意）
aux_links:
  "GitHub Repository": "https://github.com/maruru2100/sf6-stats-visualizer"